# Generated by Django 2.1.4 on 2018-12-17 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('card_pic', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=255)),
                ('expired_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
    ]
