# Generated by Django 2.1.4 on 2018-12-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='store',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
