# Generated by Django 2.1.4 on 2018-12-18 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0002_deal_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='buyers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='list of buyers'),
        ),
    ]
