# Generated by Django 2.1.4 on 2018-12-18 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0003_deal_buyers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField(default=0)),
                ('customer_field_1_desc', models.CharField(max_length=10)),
                ('customer_field_1_val', models.CharField(max_length=10)),
                ('customer_field_2_dec', models.CharField(max_length=10)),
                ('customer_field_2_val', models.CharField(max_length=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
