# Generated by Django 2.1.4 on 2018-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_deal_target_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
