# Generated by Django 2.1.4 on 2018-12-18 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_auto_20181218_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='buyers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='list of buyers'),
        ),
    ]
