# Generated by Django 2.1.4 on 2018-12-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_auto_20181218_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deal.Deal'),
            preserve_default=False,
        ),
    ]
