# Generated by Django 2.1.4 on 2018-12-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_item_deal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='customer_field_1_desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='customer_field_1_val',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='customer_field_2_dec',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='customer_field_2_val',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
