# Generated by Django 2.1.4 on 2018-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0010_auto_20181218_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
