# Generated by Django 2.1.4 on 2018-12-19 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0011_item_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0.0)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer_field_1_val', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_field_2_val', models.CharField(blank=True, max_length=10, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Deal')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='customer_field_1_val',
        ),
        migrations.RemoveField(
            model_name='item',
            name='customer_field_2_val',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Item'),
        ),
    ]
