# Generated by Django 2.1.4 on 2018-12-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0013_auto_20181219_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
        migrations.RemoveField(
            model_name='order',
            name='author_confirmed',
        ),
    ]
