# Generated by Django 2.1.4 on 2018-12-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0016_deal_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='customer_field_2_dec',
        ),
    ]
